"""
build_report.py - assemble the PDB-cohort robustness report in one folder.

Produces, under pdb_robustness/:
  data/   matched_af2_cohort_pca_ready.csv   (N=876, domain-matched, no ribosomal; PCA-notebook ready)
          pdb_cohort_pca_ready.csv           (the 876 experimental-PDB cohort; PCA-notebook ready)
          property_importance_{pdb,af2_matched}.csv
  figures/ fig_composition.{png,pdf}  fig_property_importance.{png,pdf}
           fig_variance_decomposition.{png,pdf}  fig_elo.{png,pdf}
  tables/  table_composition.tex  table_vd_cohort.tex  table_vd_pdb_vs_af2.tex
           table_elo.tex  table_property_importance.tex

Re-runnable: pick up new model scores by re-running the cohort merge first, then this.
"""
import importlib.util, shutil, sys, warnings
from pathlib import Path
import numpy as np, pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

warnings.filterwarnings("ignore")
REPO = Path(__file__).resolve().parent.parent
HERE = Path(__file__).resolve().parent
DATA, FIG, TAB = HERE / "data", HERE / "figures", HERE / "tables"
for d in (DATA, FIG, TAB):
    d.mkdir(parents=True, exist_ok=True)

IC = REPO / "design" / "outputs" / "independent_cohort"
MAIN = REPO / "dataset_update" / "main_plus_r2_r3_analysis_v12_cli.csv"
COHORT_SCORED = IC / "cohort_pdb_scored.csv"
COHORT_VD = IC / "cohort_score_variance_decomposition.csv"
COHORT_ELO = IC / "elo_cohort_unweighted" / "cohort_elo_domain_summary.csv"
AF2_VD = IC / "matched_af2_vd_control.csv"
AF2_ELO = IC / "matched_af2_elo_control.csv"

SEQF = ["sequence_length", "mw_per_residue", "isoelectric_point", "charge_at_ph7",
        "acidic_residue_fraction", "basic_residue_fraction", "gravy", "aromaticity",
        "instability_index", "proline_fraction", "small_residue_fraction"]
STRUCTF = ["ordered_percent", "helix_sheet_contrast", "rco", "avg_cb_distance", "surface_exposure"]
FEATS = SEQF + STRUCTF
TARGET = {"Eukaryota": 396, "Bacteria": 364, "Archaea": 116}   # PDB cohort domain marginal
SEED = 1000

# canonical name -> (col, type) for the cohort panel (ProGen2 = the XL column the cohort uses)
PANEL = {
    "ProteinMPNN": ("proteinmpnn_score", "structure"), "SolubleMPNN": ("solublempnn_score", "structure"),
    "Caliby": ("caliby_score", "structure"), "SolubleCaliby": ("soluble_caliby_score", "structure"),
    "ESM-IF": ("esmif_score", "structure"),
    "MIF": ("mif_score", "hybrid"), "MIF-ST": ("mifst_score", "hybrid-ST"),
    "CARP-640M": ("carp_640M_score", "sequence"), "ProGen2-XL": ("progen2_XL_score", "sequence"),
    "ProtGPT2": ("protgpt2_score", "sequence"), "ESMC-6B": ("esmc_6b_score", "sequence"),
}
ORDER = list(PANEL)   # structure -> hybrid -> sequence
TYPE_C = {"structure": "#2E7D32", "hybrid": "#F9A825", "hybrid-ST": "#C0CA33", "sequence": "#00838F"}


def _fmt(v, floatfmt):
    try:
        if pd.isna(v):
            return "--"
    except (TypeError, ValueError):
        pass
    if isinstance(v, (int, np.integer)):
        return str(int(v))
    if isinstance(v, float):
        return floatfmt % v
    # string cell: escape underscores that are not already escaped (feature names)
    return str(v).replace("\\_", "§").replace("_", "\\_").replace("§", "\\_")


def to_tex(df, path, caption, label, floatfmt="%.3f"):
    """Minimal booktabs tabular writer (no jinja2 dependency). Column headers are
    assumed already LaTeX-safe; cell strings are escaped for %, &, _ only when not
    already containing a backslash command."""
    ncol = df.shape[1]
    align = "l" + "r" * (ncol - 1)
    head = " & ".join(str(c) for c in df.columns) + " \\\\"
    lines = []
    for _, row in df.iterrows():
        cells = [_fmt(v, floatfmt) for v in row]
        lines.append(" & ".join(cells) + " \\\\")
    body = ("\\begin{tabular}{" + align + "}\n\\toprule\n" + head + "\n\\midrule\n"
            + "\n".join(lines) + "\n\\bottomrule\n\\end{tabular}\n")
    tex = ("% auto-generated by pdb_robustness/build_report.py\n"
           "\\begin{table}[ht]\\centering\\small\n"
           f"\\caption{{{caption}}}\\label{{{label}}}\n{body}\\end{{table}}\n")
    path.write_text(tex)


# ---------------------------------------------------------------- data exports
def build_matched_af2(present_models):
    main = pd.read_csv(MAIN, low_memory=False)
    pool = main[main.domain.isin(TARGET)]
    pool = pool[~pool["broad_function"].astype(str).str.contains("ribosom", case=False)]
    cols_needed = FEATS + ["protein_family", "species"] + [PANEL[m][0] for m in present_models]
    pool = pool.dropna(subset=[c for c in cols_needed if c in pool.columns])
    parts = [pool[pool.domain == d].sample(n=min(n, int((pool.domain == d).sum())), random_state=SEED)
             for d, n in TARGET.items()]
    sub = pd.concat(parts).reset_index(drop=True)
    keep = (["Entry", "domain", "species", "protein_family", "broad_function"]
            + (["avg_plddt"] if "avg_plddt" in sub.columns else [])
            + FEATS + [c for c in sub.columns if c.endswith("_score")])
    sub = sub[[c for c in keep if c in sub.columns]]
    sub = sub.drop(columns=[c for c in sub.columns if "triflow" in c.lower()])  # excluded from analysis
    out = DATA / "matched_af2_cohort_pca_ready.csv"
    sub.to_csv(out, index=False)
    print(f"matched AF2 cohort -> {out.name}  (n={len(sub)}, seed={SEED})")
    return sub


def export_pdb_pca_ready():
    df = pd.read_csv(COHORT_SCORED)
    df = df.drop(columns=[c for c in df.columns if "triflow" in c.lower()])  # excluded from analysis
    out = DATA / "pdb_cohort_pca_ready.csv"
    df.to_csv(out, index=False)
    print(f"PDB cohort        -> {out.name}  (n={len(df)})")
    return df


# ---------------------------------------------------------------- composition
def composition(pdb, af2):
    main = pd.read_csv(MAIN, low_memory=False)
    main = main[main.domain.isin(TARGET)]

    def summ(df, name):
        n = len(df)
        dom = df["domain"].value_counts(normalize=True) * 100
        rib = df["broad_function"].astype(str).str.contains("ribosom", case=False).mean() * 100
        return dict(cohort=name, n=n,
                    pct_Archaea=dom.get("Archaea", 0), pct_Bacteria=dom.get("Bacteria", 0),
                    pct_Eukaryota=dom.get("Eukaryota", 0), pct_ribosomal=rib,
                    median_len=df["sequence_length"].median(), median_pI=df["isoelectric_point"].median(),
                    n_species=df["species"].nunique(), n_families=df["protein_family"].nunique())

    rows = [summ(pdb, "PDB cohort (experimental)"), summ(af2, "AF2 matched (N=876)"),
            summ(main, "AF2 full (3-domain)")]
    comp = pd.DataFrame(rows)
    tcols = {"cohort": "Cohort", "n": "n", "pct_Archaea": "\\% Arch", "pct_Bacteria": "\\% Bact",
             "pct_Eukaryota": "\\% Euk", "pct_ribosomal": "\\% ribo", "median_len": "med.\\ len",
             "median_pI": "med.\\ pI", "n_species": "species", "n_families": "families"}
    to_tex(comp.rename(columns=tcols), TAB / "table_composition.tex",
           "Composition of the experimental-PDB cohort, the matched AF2 subsample, and the full "
           "3-domain AF2 set.", "tab:pdb-composition", floatfmt="%.1f")

    # figure: domain proportions, ribosomal %, length & pI distributions
    fig, ax = plt.subplots(2, 2, figsize=(11, 8))
    labels = ["PDB cohort", "AF2 matched", "AF2 full"]
    dfs = [pdb, af2, main]
    cpal = ["#1976D2", "#F57C00", "#9E9E9E"]
    # (a) domain proportions
    doms = ["Archaea", "Bacteria", "Eukaryota"]
    x = np.arange(len(doms)); w = 0.26
    for i, (df, lab) in enumerate(zip(dfs, labels)):
        p = df["domain"].value_counts(normalize=True) * 100
        ax[0, 0].bar(x + (i - 1) * w, [p.get(d, 0) for d in doms], w, label=lab, color=cpal[i])
    ax[0, 0].set_xticks(x); ax[0, 0].set_xticklabels(doms); ax[0, 0].set_ylabel("% of cohort")
    ax[0, 0].set_title("Domain composition (matched by design)"); ax[0, 0].legend(fontsize=8)
    # (b) ribosomal %
    ribs = [df["broad_function"].astype(str).str.contains("ribosom", case=False).mean() * 100 for df in dfs]
    ax[0, 1].bar(labels, ribs, color=cpal)
    ax[0, 1].set_ylabel("% ribosomal"); ax[0, 1].set_title("Ribosomal fraction")
    for i, v in enumerate(ribs):
        ax[0, 1].text(i, v + 0.4, f"{v:.0f}%", ha="center", fontsize=9)
    # (c) length
    for df, lab, c in zip(dfs, labels, cpal):
        ax[1, 0].hist(df["sequence_length"].clip(upper=1000), bins=40, histtype="step",
                      density=True, label=lab, color=c, lw=1.8)
    ax[1, 0].set_xlabel("sequence length (aa)"); ax[1, 0].set_ylabel("density")
    ax[1, 0].set_title("Length distribution"); ax[1, 0].legend(fontsize=8)
    # (d) pI
    for df, lab, c in zip(dfs, labels, cpal):
        ax[1, 1].hist(df["isoelectric_point"], bins=40, histtype="step",
                      density=True, label=lab, color=c, lw=1.8)
    ax[1, 1].set_xlabel("isoelectric point"); ax[1, 1].set_ylabel("density")
    ax[1, 1].set_title("Isoelectric-point distribution"); ax[1, 1].legend(fontsize=8)
    fig.suptitle("Cohort composition: experimental-PDB vs AF2 (matched & full)", fontsize=13)
    fig.tight_layout(rect=[0, 0, 1, 0.97])
    fig.savefig(FIG / "fig_composition.png", dpi=150); fig.savefig(FIG / "fig_composition.pdf")
    plt.close(fig)
    print("wrote fig_composition + table_composition")
    return comp


# ---------------------------------------------------------------- property importance
def property_importance(pdb, af2, present_models):
    spec = importlib.util.spec_from_file_location(
        "propimp", REPO / "paper_code" / "04_property_importance" / "property_importance.py")
    PI = importlib.util.module_from_spec(spec); spec.loader.exec_module(PI)
    models = {m: PANEL[m][0] for m in present_models}
    rp = PI.analyse(pdb, models, "PDB"); rp["cohort"] = "PDB"
    ra = PI.analyse(af2, models, "AF2"); ra["cohort"] = "AF2_matched"
    rp.to_csv(DATA / "property_importance_pdb.csv", index=False)
    ra.to_csv(DATA / "property_importance_af2_matched.csv", index=False)

    # table: top-3 properties by relative weight per model, both cohorts
    def top3(df):
        out = {}
        for m, g in df.groupby("model"):
            g = g.sort_values("rel_weight_pct", ascending=False).head(3)
            out[m] = ", ".join(f"{r.property} ({r.rel_weight_pct:.0f}\\%)" for r in g.itertuples())
        return out
    tp, ta = top3(rp), top3(ra)
    r2p = rp.groupby("model").model_R2.first(); r2a = ra.groupby("model").model_R2.first()
    rows = [dict(Model=m, **{"$R^2$ (PDB)": r2p.get(m, np.nan),
                             "Top properties (PDB)": tp.get(m, ""),
                             "$R^2$ (AF2)": r2a.get(m, np.nan),
                             "Top properties (AF2 matched)": ta.get(m, "")})
            for m in present_models if m in tp]
    to_tex(pd.DataFrame(rows), TAB / "table_property_importance.tex",
           "Top biophysical properties by Johnson relative weight (\\% of model $R^2$) for each "
           "model, on the experimental-PDB cohort vs the matched AF2 subsample.",
           "tab:pdb-propimp", floatfmt="%.2f")

    # figure: rel weight of the dominant structural feature (avg_cb_distance / rco) and a
    # composition feature (acidic_residue_fraction) - PDB vs AF2 - for all models
    feats_show = ["avg_cb_distance", "rco", "acidic_residue_fraction", "isoelectric_point"]
    fig, axes = plt.subplots(1, len(feats_show), figsize=(15, 5), sharey=True)
    x = np.arange(len(present_models)); w = 0.4
    for k, feat in enumerate(feats_show):
        pv = [rp[(rp.model == m) & (rp.property == feat)].rel_weight_pct.mean() for m in present_models]
        av = [ra[(ra.model == m) & (ra.property == feat)].rel_weight_pct.mean() for m in present_models]
        axes[k].bar(x - w / 2, pv, w, label="PDB", color="#1976D2")
        axes[k].bar(x + w / 2, av, w, label="AF2 matched", color="#F57C00")
        axes[k].set_title(feat, fontsize=10); axes[k].set_xticks(x)
        axes[k].set_xticklabels(present_models, rotation=60, ha="right", fontsize=7)
        if k == 0:
            axes[k].set_ylabel("relative weight (% of model R²)"); axes[k].legend(fontsize=8)
    fig.suptitle("Property→score importance: experimental-PDB vs matched AF2", fontsize=13)
    fig.tight_layout(rect=[0, 0, 1, 0.96])
    fig.savefig(FIG / "fig_property_importance.png", dpi=150)
    fig.savefig(FIG / "fig_property_importance.pdf"); plt.close(fig)
    print("wrote fig_property_importance + table_property_importance")


# ---------------------------------------------------------------- VD
def variance_decomposition():
    cv = pd.read_csv(COHORT_VD)
    ctrl = pd.read_csv(AF2_VD)
    cv = cv[cv["model"].isin(ORDER)].set_index("model").reindex(ORDER).reset_index()

    tcols = {"model": "Model", "type": "Type", "n": "n", "R2_Biophys": "Biophys $R^2$",
             "dSpecies_given_family_biophys": "$\\Delta$spec (raw)",
             "residual_species_R2_adj": "$\\Delta$spec (adj)",
             "species_attenuation": "atten.",
             "species_effect_retention_given_family_biophys": "retention",
             "species_p_given_family_biophys": "$p$"}
    keep = list(tcols)
    to_tex(cv[keep].rename(columns=tcols), TAB / "table_vd_cohort.tex",
           "Score-variance decomposition on the experimental-PDB cohort (per-model complete case; "
           "14-feature biophysics, protein family, species). $\\Delta$spec = residual species "
           "variance beyond family+biophysics; retention = within-family per-species effect "
           "retention (Simpson's check).", "tab:pdb-vd")

    cmp = ctrl[["model", "type", "PDB_resid_raw", "AF2_resid_raw_mean", "AF2_resid_raw_sd",
                "PDB_resid_adj", "AF2_resid_adj_mean", "PDB_retention", "AF2_retention_mean"]].copy()
    cmp["model"] = pd.Categorical(cmp["model"], ORDER, ordered=True)
    cmp = cmp.sort_values("model")
    ren = {"model": "Model", "type": "Type", "PDB_resid_raw": "$\\Delta$spec PDB",
           "AF2_resid_raw_mean": "$\\Delta$spec AF2", "AF2_resid_raw_sd": "AF2 sd",
           "PDB_resid_adj": "adj PDB", "AF2_resid_adj_mean": "adj AF2",
           "PDB_retention": "ret.\\ PDB", "AF2_retention_mean": "ret.\\ AF2"}
    to_tex(cmp.rename(columns=ren), TAB / "table_vd_pdb_vs_af2.tex",
           "Residual species variance: experimental-PDB cohort vs matched AF2 subsample "
           "(AF2 = mean over 30 N- and composition-matched draws).", "tab:pdb-vs-af2-vd")

    # figure: residual species (raw) PDB vs AF2-matched + retention
    fig, ax = plt.subplots(1, 2, figsize=(13, 5.2))
    m = ctrl.set_index("model").reindex(ORDER)
    x = np.arange(len(ORDER)); w = 0.4
    cols = [TYPE_C[PANEL[k][1]] for k in ORDER]
    ax[0].bar(x - w / 2, m["PDB_resid_raw"], w, label="PDB cohort", color="#1976D2")
    ax[0].bar(x + w / 2, m["AF2_resid_raw_mean"], w, yerr=m["AF2_resid_raw_sd"],
              label="AF2 matched", color="#F57C00", capsize=2)
    ax[0].set_ylabel("residual species $R^2$ (raw)")
    ax[0].set_title("Residual species variance beyond family+biophysics")
    ax[1].bar(x - w / 2, m["PDB_retention"], w, label="PDB cohort", color="#1976D2")
    ax[1].bar(x + w / 2, m["AF2_retention_mean"], w, yerr=m["AF2_retention_sd"],
              label="AF2 matched", color="#F57C00", capsize=2)
    ax[1].axhline(0, color="k", lw=0.6)
    ax[1].set_ylabel("within-family per-species retention")
    ax[1].set_title("Simpson's-check retention (→1 genuine, →0 family-driven)")
    seq_start = [PANEL[k][1] for k in ORDER].index("sequence")
    for a in ax:
        a.set_xticks(x); a.set_xticklabels(ORDER, rotation=55, ha="right", fontsize=8)
        a.axvline(seq_start - 0.5, color="k", ls="--", lw=0.8, alpha=0.4)
        a.legend(fontsize=9); a.grid(axis="y", alpha=0.2)
    fig.suptitle("Variance decomposition: experimental-PDB cohort vs matched AF2", fontsize=13)
    fig.tight_layout(rect=[0, 0, 1, 0.96])
    fig.savefig(FIG / "fig_variance_decomposition.png", dpi=150)
    fig.savefig(FIG / "fig_variance_decomposition.pdf"); plt.close(fig)
    print("wrote fig_variance_decomposition + table_vd_cohort + table_vd_pdb_vs_af2")


# ---------------------------------------------------------------- ELO
def elo():
    col2name = {v[0]: k for k, v in PANEL.items()}
    ce = pd.read_csv(COHORT_ELO)
    ce["Model"] = ce["model"].map(lambda c: col2name.get(c, c))
    ce = ce[ce["Model"].isin(ORDER)].copy()
    ce["Model"] = pd.Categorical(ce["Model"], ORDER, ordered=True)
    ce = ce.sort_values("Model")
    tcols = {"Model": "Model", "Archaea": "Archaea", "Bacteria": "Bacteria",
             "Eukaryota": "Eukaryota", "Arch_minus_Euk": "Arch$-$Euk", "top_domain": "top"}
    to_tex(ce[list(tcols)].rename(columns=tcols), TAB / "table_elo.tex",
           "Mean species Elo by domain on the experimental-PDB cohort (unweighted; 50 permutations) "
           "and the Archaea$-$Eukaryota gap.", "tab:pdb-elo", floatfmt="%.0f")

    ctrl = pd.read_csv(AF2_ELO).set_index("model").reindex(ORDER)
    fig, ax = plt.subplots(figsize=(11, 5.4))
    x = np.arange(len(ORDER)); w = 0.4
    pdbgap = ce.set_index("Model").reindex(ORDER)["Arch_minus_Euk"]
    ax.bar(x - w / 2, pdbgap.values, w, label="PDB cohort", color="#1976D2")
    ax.bar(x + w / 2, ctrl["AF2_arch_minus_euk_mean"], w, yerr=ctrl["AF2_arch_minus_euk_sd"],
           label="AF2 matched", color="#F57C00", capsize=2)
    ax.axhline(0, color="k", lw=0.8)
    seq_start = [PANEL[k][1] for k in ORDER].index("sequence")
    ax.axvline(seq_start - 0.5, color="k", ls="--", lw=0.8, alpha=0.4)
    ax.set_xticks(x); ax.set_xticklabels(ORDER, rotation=55, ha="right")
    ax.set_ylabel("Archaea − Eukaryota Elo gap")
    ax.set_title("Species Elo: Archaea−Eukaryota preference, PDB cohort vs matched AF2\n"
                 "(>0 prefers Archaea, <0 prefers Eukaryota)")
    ax.legend(); ax.grid(axis="y", alpha=0.2)
    fig.tight_layout()
    fig.savefig(FIG / "fig_elo.png", dpi=150); fig.savefig(FIG / "fig_elo.pdf"); plt.close(fig)
    print("wrote fig_elo + table_elo")


def main():
    present = [m for m in ORDER if PANEL[m][0] in pd.read_csv(COHORT_SCORED, nrows=1).columns]
    pdb = export_pdb_pca_ready()
    af2 = build_matched_af2(present)
    composition(pdb, af2)
    property_importance(pdb, af2, present)
    variance_decomposition()
    elo()
    print("\nReport built under pdb_robustness/")


if __name__ == "__main__":
    main()
